version: "3.4"

services:
#  nginx-proxy:
#    build: nginx
#    ports:
#      - "8088:8080"

  mysql-mission7:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pp123456
      MYSQL_DATABASE: gec_mission7

  app-mission7:
    build: mission7-the-last-course
    ports:
      - 8080:8080
    links:
      - mysql-mission7