--INSERT INTO tbl_product(product_name, price, quantity) VALUES('Ipad',1000,7);
--INSERT INTO tbl_product(product_name, price, quantity) VALUES('Pen',17,23);
--INSERT INTO tbl_product(product_name, price, quantity) VALUES('Head Phone',490,12);
--INSERT INTO tbl_product(product_name, price, quantity) VALUES('Monitor LED',2700,3);