INSERT INTO tbl_products(id, name, price, quantity) VALUES(1,"Pen",5,170);
INSERT INTO tbl_products(id, name, price, quantity) VALUES(2,"Monitor",2900,12);
INSERT INTO tbl_products(id, name, price, quantity) VALUES(3,"Land Cable",150,32);
INSERT INTO tbl_products(id, name, price, quantity) VALUES(4,"Mouse",3900,11);
INSERT INTO tbl_products(id, name, price, quantity) VALUES(5,"HDMI Adapter",89,58);
INSERT INTO tbl_products(id, name, price, quantity) VALUES(6,"Pencil",12,300);
INSERT INTO tbl_products(id, name, price, quantity) VALUES(7,"Table",450,7);
INSERT INTO tbl_products(id, name, price, quantity) VALUES(8,"Ram DDR4 4GB",990,22);
INSERT INTO tbl_products(id, name, price, quantity) VALUES(9,"Keybord",1590,14);
INSERT INTO tbl_products(id, name, price, quantity) VALUES(10,"Backpack",1990,7);